### ISSUE TITLE
ETCd crash after few days

### ISSUE THREAD

**Issue by Vrtak-CZ** [kubernetes-incubator/kube-aws#691]
Hello,

we experience crash 2 of 3 etcd servers see logs bellow. But what is really bad we have no access to whole k8s cluster due etcd errors (timeout).

```
core@ip-10-101-3-236 ~ $ journalctl -u etcdadm-check.service -f

-- Logs begin at Wed 2017-05-31 22:08:13 UTC. --
Jun 02 15:38:09 ip-10-101-3-236.eu-west-1.compute.internal systemd[1]: etcdadm-check.service: Unit entered failed state.
Jun 02 15:38:09 ip-10-101-3-236.eu-west-1.compute.internal systemd[1]: etcdadm-check.service: Failed with result 'timeout'.
Jun 02 15:38:21 ip-10-101-3-236.eu-west-1.compute.internal systemd[1]: Starting etcd health check...
Jun 02 15:38:24 ip-10-101-3-236.eu-west-1.compute.internal systemctl[11792]: active
Jun 02 15:38:27 ip-10-101-3-236.eu-west-1.compute.internal etcdadm[11806]: declare -x ETCDCTL_CACERT="/etc/ssl/certs/ca.pem"
Jun 02 15:38:27 ip-10-101-3-236.eu-west-1.compute.internal etcdadm[11806]: declare -x ETCDCTL_CA_FILE="/etc/ssl/certs/ca.pem"
Jun 02 15:38:27 ip-10-101-3-236.eu-west-1.compute.internal etcdadm[11806]: declare -x ETCDCTL_CERT="/etc/ssl/certs/etcd-client.pem"
Jun 02 15:38:27 ip-10-101-3-236.eu-west-1.compute.internal etcdadm[11806]: declare -x ETCDCTL_CERT_FILE="/etc/ssl/certs/etcd-client.pem"
Jun 02 15:38:27 ip-10-101-3-236.eu-west-1.compute.internal etcdadm[11806]: declare -x ETCDCTL_KEY="/etc/ssl/certs/etcd-client-key.pem"
Jun 02 15:38:27 ip-10-101-3-236.eu-west-1.compute.internal etcdadm[11806]: declare -x ETCDCTL_KEY_FILE="/etc/ssl/certs/etcd-client-key.pem"
Jun 02 15:40:24 ip-10-101-3-236.eu-west-1.compute.internal systemd[1]: etcdadm-check.service: Start operation timed out. Terminating.
Jun 02 15:40:25 ip-10-101-3-236.eu-west-1.compute.internal systemd[1]: etcdadm-check.service: Main process exited, code=killed, status=15/TERM
Jun 02 15:41:25 ip-10-101-3-236.eu-west-1.compute.internal systemctl[11871]: active
Jun 02 15:40:28 ip-10-101-3-236.eu-west-1.compute.internal systemd[1]: Failed to start etcd health check.
Jun 02 15:40:28 ip-10-101-3-236.eu-west-1.compute.internal systemd[1]: etcdadm-check.service: Unit entered failed state.
Jun 02 15:40:28 ip-10-101-3-236.eu-west-1.compute.internal systemd[1]: etcdadm-check.service: Failed with result 'timeout'.
```

relevant configuration:

```
etcd:
  count: 3
  instanceType: t2.medium
  subnets:
    - name: ManagementPrivateSubnet1
    - name: ManagementPrivateSubnet2
    - name: ManagementPrivateSubnet3

  snapshot:
    automated: true
  disasterRecovery:
    automated: true

  kmsKeyArn: 'arn:aws:kms:eu-west-1:xxxxxxxxxxxx:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
  dataVolume:
    encrypted: true

  memberIdentityProvider: eni
```

used version `kube-aws version v0.9.7-rc.2`

please ping me if you want more information.

**Comment by Vrtak-CZ** [comment]
it should be because of CPU credits because it uses ~2 per 5mins with is ~24/hour and t2.medium has 24 credits per hour. Still investigating

**Comment by trinitronx** [comment]
This one may be a duplicate of #660, and _might_ be caused by #640 

Current theory is that `awscli` docker containers started by `etcdadm-*` scripts without `--rm` build up on the system over time.  This either causes disk space to fill up then causing `etcd` to fail, or causes the failure some other way (maybe too many hardlinks from docker container layers?)

Additionally, the `etcdadm-reconfigure` service may not be fully reliable when trying to restore `etcd` snapshots.  So this prevents the cluster from auto-recovering.

Check your logs in journald:

    journalctl -u etcd-member
    journalctl -u etcdadm-reconfigure
    systemctl status etcdadm-reconfigure
    systemctl status etcd-member

Compare to the output & debugging results I posted in #660

**Comment by mumoshu** [comment]
@Vrtak-CZ Thanks for the report!
I do suspect this is caused by low cpu credit because we are not seeing any visible errors before `etcdadm-check.service: Start operation timed out. Terminating.`.
Probably you're already trying but a graph of cpu credit history would help.

**Comment by mumoshu** [comment]
@trinitronx Thanks for chiming in 👍 
Just confirmation but AFAICS, @Vrtak-CZ is using kube-aws version v0.9.7-rc.2, which should not be affected by #640 which is fixed since v0.9.7-rc.1 via #641

**Comment by Vrtak-CZ** [comment]
Just little update for you. We switched our Etcd instances to `m3.medium` on Friday (2017-06-02). And this problem is back now. When I look in to monitoring ...

- Etcd-1 has 1.5% CPU Utilization
- Etcd-2 has 100% CPU Utilization
- Etcd-3 has 100% CPU Utilization

There is CPU Utilization graph for Etcd-2

<img width="915" alt="screen shot 2017-06-07 at 15 34 02" src="https://user-images.githubusercontent.com/112567/26881225-1bfebc08-4b97-11e7-9b80-0ee0c4f3cd50.png">

We don't make any change in this cluster from the moment when we switched to m3.medium.

On this cluster we have 2 worker nodes with 2x3pods (with 2 services and 2 ingress).

There is screenshot of TOP from Etcd-3

<img width="1131" alt="screen shot 2017-06-07 at 15 39 06" src="https://user-images.githubusercontent.com/112567/26881550-0b11f71a-4b98-11e7-9336-89d2c78774f3.png">

**Comment by Vrtak-CZ** [comment]
And this error occurs just now

```
ilay:~:% ssh -i .ssh-special/goodbaby-aws core@10.101.4.82
Last login: Wed Jun  7 13:25:08 UTC 2017 from 10.11.8.31 on pts/0
Container Linux by CoreOS stable (1353.8.0)
Update Strategy: No Reboots
Failed Units: 1
  user@0.service
core@ip-10-101-4-82 ~ $ journalctl -u user@0.service -f
-- Logs begin at Mon 2017-06-05 23:38:36 UTC. --
Jun 07 13:38:20 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: user@0.service: Failed with result 'start-limit-hit'.
Jun 07 13:38:20 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: user@0.service: Start request repeated too quickly.
Jun 07 13:38:20 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: Failed to start User Manager for UID 0.
Jun 07 13:38:20 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: user@0.service: Failed with result 'start-limit-hit'.
Jun 07 13:38:21 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: user@0.service: Start request repeated too quickly.
Jun 07 13:38:21 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: Failed to start User Manager for UID 0.
Jun 07 13:38:21 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: user@0.service: Failed with result 'start-limit-hit'.
Jun 07 13:38:22 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: user@0.service: Start request repeated too quickly.
Jun 07 13:38:22 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: Failed to start User Manager for UID 0.
Jun 07 13:38:22 ip-10-101-4-82.eu-west-1.compute.internal systemd[1]: user@0.service: Failed with result 'start-limit-hit'.
```

**Comment by danielfm** [comment]
@Vrtak-CZ What is the size/IOPS of the EBS volumes you are using in your etcd instances? Can you check the read/write throughput, burst balance, etc, to see if there's anything weird going on there?

**Comment by danielfm** [comment]
Also, your print showing the `top`command shows that this instance only has about ~85MB of free memory, which is dangerously low.

**Comment by Vrtak-CZ** [comment]
We are using kube-aws defaults for EBS with is gp2.

> Also, your print showing the topcommand shows that this instance only has about ~85MB of free memory, which is dangerously low.

Good catch it looks weird. It looks like Etcd-2 and Etcd-3 consumes lot of resources (CPU, RAM) but Etcd-1 looks ok it has 2GB free.

**Comment by danielfm** [comment]
One more thing, if you are able to log into these instances via SSH, you could run some of the commands shown [here](https://medium.com/netflix-techblog/linux-performance-analysis-in-60-000-milliseconds-accc10403c55) to try to find what's causing the system to degrade. (Use [toolbox](https://coreos.com/os/docs/latest/install-debugging-tools.html) and `yum install sysstat` to install some of the tools that are not included in Container Linux by default)

**Comment by Vrtak-CZ** [comment]
Sure but i'm just rebooted these instances and they currently running as expected. So when this problem occurs i'll try to get more information.

**Comment by mumoshu** [comment]
Hi @Vrtak-CZ @danielfm @trinitronx, thanks for the valuable feedbacks on this :bow:

Recently I've been unable to reproduce this issue on latest masters of kube-aws.
Also, thanks to @ytsarev's latest work to fix the serious memory leak coming from rkt called by etcdadm, our etcd clusters with the automatic disaster recovery feature enabled would even more be stabilized.

I'll keep testing for a while anyway but JFYI.

**Comment by mumoshu** [comment]
fyi v0.9.7-rc.4 has just been released with all the known fixes

**Comment by ytsarev** [comment]
jfyi guys, we still had a memory problem with *leader* when running etcd `v3.1.8` . Upgrade to `v3.2.1` showed much more consistent memory behavior. Our bet was on https://github.com/coreos/etcd/pull/7758 and so far it looks like it helped a lot.

**Comment by redbaron** [comment]
@ytsarev , did 3.2.1 work for you out of the box with no tweaking to kube-aws setup?

**Comment by ytsarev** [comment]
@redbaron out of the box, no tweaking required

**Comment by ytsarev** [comment]
Additional fix that was done around `etcdadm` optimization i forgot to share:
https://github.com/kubernetes-incubator/kube-aws/pull/722
